FROM debian:latest

# Install base dependencies
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y sudo curl ffmpeg git locales nano python3-pip screen ssh unzip wget autossh

# Set up locale
RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

# Install Node.js (optional - remove if not needed)
RUN curl -sL https://deb.nodesource.com/setup_21.x | bash - && \
    apt-get install -y nodejs

# Configure SSH
RUN mkdir -p /run/sshd && \
    mkdir -p /root/.ssh && \
    echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFshKeW/SRrfepjUPfA8LfZRg3sqX4rKhrSXB5w6K1Li Generated By Termius' > /root/.ssh/authorized_keys && \
    chmod 700 /root/.ssh && \
    chmod 600 /root/.ssh/authorized_keys && \
    echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config && \
    echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config && \
    echo 'root:choco' | chpasswd && \
    ssh-keygen -A

# Create web content
RUN mkdir -p /var/www && \
    echo "<html><body><h1>Python HTTP Server Working!</h1><p>Access SSH via Serveo tunnel</p></body></html>" > /var/www/index.html

# Create startup script
RUN echo "#!/bin/sh" > /start && \
    echo "# Start Python HTTP server (local only)" >> /start && \
    echo "cd /var/www && python3 -m http.server 8000 &" >> /start && \
    echo "" >> /start && \
    echo "# Start Serveo SSH tunnel (SSH only)" >> /start && \
    echo "autossh -M 0 -o 'ServerAliveInterval 60' -o 'ServerAliveCountMax 3' \\" >> /start && \
    echo "    -N -R 0:localhost:22 serveo.net &" >> /start && \
    echo "" >> /start && \
    echo "# Start SSH server" >> /start && \
    echo "/usr/sbin/sshd -D" >> /start && \
    chmod 755 /start

# Expose ports
EXPOSE 8000 22

# Start command
CMD /start
